### ISSUE TITLE
The gazebo velocities are off

### ISSUE THREAD

**Issue by rickstaa** [rickstaa/panda-gazebo#8]
It appears that there is something wrong with the robot velocities given by the `joint_states` topic. Some of the velocities are non-zero when the robot is not moving. The velocities are off the most in panda_joints `1, 3, 5, 7`. From the twist, it can be seen that the angular velocity around the `z-axis` of the world frame is said to be non-zero when the robot is not moving. Wrong inertias or masses likely cause this. This can also be seen from the behaviour of the robot when all controllers are turned off:

![robot_instability](https://user-images.githubusercontent.com/17570430/77158750-37b4d480-6aa4-11ea-84f0-b414ada5b059.gif)

It can also be seen when we use the `panda_arm_controller` and `panda_hand_controller` joint trajectory controllers. In that case, some tremor can be seen in the robot:

![robot_tremor](https://user-images.githubusercontent.com/17570430/77158909-8bbfb900-6aa4-11ea-907f-91fd91fedf31.gif)

#### Joint_states message
```
---
header:
  seq: 9150
  stamp:
    secs: 183
    nsecs: 338000000
  frame_id: ''
name: [panda_finger_joint1, panda_finger_joint2, panda_joint1, panda_joint2, panda_joint3,
  panda_joint4, panda_joint5, panda_joint6, panda_joint7]
position: [0.0003354834018347102, 0.010066464352654103, 0.6999165422791744, 0.0965460563297098, -0.23107617775252542, -0.06987614210995119, -0.021742634164866104, -0.01751297536257379, 0.9311505772830095]
velocity: [0.024139134504268925, -0.03771701649679839, 5.015356581026765, 0.0778556915365698, -7.390148038208395, -0.05268650246505116, 2.6458660211836764, -0.022327588959045387, 0.3610315628725411]
effort: [0.17243708126948037, -0.0941726114359864, 87.0, -1.7835241508442152, -87.0, -4.177768345991017, 12.0, 0.9796109611548913, 8.069424275887098]
---
```
#### Gazebo/link_states message

```
name: ['ground_plane::link', 'panda::panda_link0', 'panda::panda_link1', 'panda::panda_link2',
  'panda::panda_link3', 'panda::panda_link4', 'panda::panda_link5', 'panda::panda_link6',
  'panda::panda_link7', 'panda::panda_leftfinger', 'panda::panda_rightfinger']
pose:
  -
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  -
    position:
      x: 1.10558102569e-06
      y: -7.26937167469e-06
      z: 1.93691628735e-05
    orientation:
      x: -6.73128128671e-05
      y: -4.53700109924e-05
      z: -0.000103824501618
      w: 0.999999991316
  -
    position:
      x: -1.76247254571e-05
      y: 4.24025075457e-05
      z: 0.333014965949
    orientation:
      x: -3.29112582649e-05
      y: 7.76744090493e-05
      z: 0.75490538126
      w: 0.65583371233
  -
    position:
      x: -1.52453056555e-05
      y: 3.99384563197e-05
      z: 0.333017210119
    orientation:
      x: -0.488959385428
      y: -0.510743359884
      z: 0.555621740555
      w: 0.43742933276
  -
    position:
      x: -0.00423536079247
      y: 0.0302467765911
      z: 0.647540183837
    orientation:
      x: -0.0398062869333
      y: 0.0273952223632
      z: 0.674534825872
      w: 0.736659846876
  -
    position:
      x: 0.00306949908635
      y: 0.112056380481
      z: 0.639777545908
    orientation:
      x: 0.475115806888
      y: 0.513287237883
      z: 0.438126882158
      w: 0.564664516861
  -
    position:
      x: -0.00696176311975
      y: 0.0941971238756
      z: 1.03200846774
    orientation:
      x: -0.0639031244763
      y: 0.0524464753222
      z: 0.664426503795
      w: 0.742767244137
  -
    position:
      x: -0.00696091934712
      y: 0.0941988225744
      z: 1.03201011033
    orientation:
      x: 0.475595150535
      y: 0.511083560224
      z: 0.427740480471
      w: 0.574143648073
  -
    position:
      x: 0.0028660161522
      y: 0.180202051338
      z: 1.01616907605
    orientation:
      x: 0.961297610779
      y: 0.259957889492
      z: -0.0213198404782
      w: 0.088737047527
  -
    position:
      x: 0.00421691976949
      y: 0.150021399122
      z: 0.853550495501
    orientation:
      x: 0.788639675649
      y: 0.608047014315
      z: -0.0536432598844
      w: 0.0738152494045
  -
    position:
      x: -0.0059995939934
      y: 0.152659468273
      z: 0.853009599175
    orientation:
      x: 0.788644099866
      y: 0.608041224817
      z: -0.0536428580391
      w: 0.0738159633893
twist:
  -
    linear:
      x: 0.0
      y: 0.0
      z: 0.0
    angular:
      x: 0.0
      y: 0.0
      z: 0.0
  -
    linear:
      x: 2.60271623935e-05
      y: 2.0100508316e-06
      z: 0.00216013980414
    angular:
      x: 0.0159317006787
      y: -0.0392074946712
      z: -0.000195889632766
  -
    linear:
      x: -0.00551182262386
      y: -0.00376186743954
      z: -0.00275520746602
    angular:
      x: -0.0173157514624
      y: 0.132527128403
      z: 5.0132816733
  -
    linear:
      x: 0.00181242052445
      y: -0.00406741199614
      z: 0.00114451855703
    angular:
      x: -0.12271526405
      y: 0.189370185061
      z: 5.01847829857
  -
    linear:
      x: -0.0902251055711
      y: 0.0148703442325
      z: -0.000925126322291
    angular:
      x: -0.0392094993475
      y: -0.470898779328
      z: -2.36616968135
  -
    linear:
      x: 0.111336263792
      y: -0.00493215338645
      z: -0.00512059492564
    angular:
      x: -0.057016729358
      y: -0.338498172705
      z: -2.28188373413
  -
    linear:
      x: -0.00105395660669
      y: 0.00836763698209
      z: 0.00138670298056
    angular:
      x: -0.0242337565211
      y: 0.250476283906
      z: 0.356931076386
  -
    linear:
      x: 0.00100894052265
      y: 0.0100511005162
      z: 0.00475185388637
    angular:
      x: -0.012667144161
      y: 0.295614894092
      z: 0.346512621853
  -
    linear:
      x: -0.0322587274726
      y: 0.0134411956432
      z: 0.000949555990236
    angular:
      x: -0.00831202622665
      y: 0.0398001612625
      z: -0.0151672271087
  -
    linear:
      x: -0.00933624953538
      y: 0.0049086994893
      z: 0.00264589430717
    angular:
      x: 0.0181174357057
      y: 0.0290164194724
      z: -0.0042234505017
  -
    linear:
      x: 0.000382584165082
      y: 0.002689650312
      z: 0.00354260107495
    angular:
      x: 0.0184136770994
      y: 0.0306787399346
      z: -0.0192355959089
---
```

#### Possible cause
From this [issue](https://github.com/ros-controls/ros_control/issues/351) it looks like the inertia/mass and COM properties of the panda robot are not stable.

#### Current Robot properties
The properties below are defined w.r.t. the definitions that are found [here](https://wiki.ros.org/urdf/XML/joint).

- **Joint damping:** `1.0 (n*m*s)/rad`

##### Panda link 0

- **mass**: `2.92`
- **com**: `xyz="-0.025566 -2.88e-05 0.057332" rpy="0 0 0"`
- **Inertia**: `ixx="0.00782229414331" ixy="-1.56191622996e-05" ixz="-0.00126005738123" iyy="0.0109027971813" iyz="1.08233858202e-05" izz="0.0102355503949"`

##### Panda link 1

- **mass**: `2.74`
- **com**: `xyz="0 -0.0324958 -0.0675818" rpy="0 0 0"`
- **Inertia**: `ixx="0.0180416958283" ixy="0.0" ixz="0.0" iyy="0.0159136071891" iyz="0.0046758424612" izz="0.00620690827127"`

##### Panda link 2

- **mass**: `2.74`
- **com**: `xyz="0 -0.06861 0.0322285" rpy="0 0 0" `
- **Inertia**: `ixx="0.0182856182281" ixy="0.0" ixz="0.0" iyy="0.00621358421175" iyz="-0.00472844221905" izz="0.0161514346309"`

##### Panda link 3

- **mass**: `2.38`
- **com**: `xyz="0.0469893 0.0316374 -0.031704" rpy="0 0 0" `
- **Inertia**: `ixx="0.00771376630908" ixy="-0.00248490625138" ixz="-0.00332147581033" iyy="0.00989108008727" iyz="-0.00217796151484" izz="0.00811723558464"`

##### Panda link 4

- **mass**: `2.38`
- **com**: `xyz="-0.0360446 0.0336853 0.031882" rpy="0 0 0"`
- **Inertia**: `ixx="0.00799663881132" ixy="0.00347095570217" ixz="-0.00241222942995" iyy="0.00825390705278" iyz="0.00235774044121" izz="0.0102515004345"`

##### Panda link 5

- **mass**: `2.74`
- **com**: `xyz="0 0.0610427 -0.104176" rpy="0 0 0"`
- **Inertia**: `ixx="0.030371374513" ixy="6.50283587108e-07" ixz="-1.05129179916e-05" iyy="0.0288752887402" iyz="-0.00775653445787" izz="0.00444134056164"`

##### Panda link 6

- **mass**: `1.55`
- **com**: `xyz="0.0510509 0.009108 0.0106343" rpy="0 0 0"`
- **Inertia**: `ixx="0.00303336450376" ixy="-0.000437276865508" ixz="0.000629257294877" iyy="0.00404479911567" iyz="0.000130472021025" izz="0.00558234286039"`

##### Panda link 7

- **mass**: `0.54`
- **com**: `xyz="0.0109695 0.0107965 0.0650411" rpy="0 0 0"`
- **Inertia**: `ixx="0.000888868887021" ixy="-0.00012239074652" ixz="3.98699829666e-05" iyy="0.000888001373233" iyz="-9.33825115206e-05" izz="0.0007176834609"`

### References:
- https://github.com/ros-controls/ros_control/issues/351
- https://answers.gazebosim.org/question/20260/gazebo-sends-wrong-velocities-when-using-joint-effort-controller/
- https://github.com/ros-simulation/gazebo_ros_pkgs/issues/830
- https://github.com/jacknlliu/development-issues/issues/27
- https://answers.ros.org/question/300756/gazebo-sends-wrong-velocities-when-using-joint-effort-controller/
- https://github.com/ros-controls/ros_controllers/issues/317
